import { connectDatabase, getCollections, resetCollections } from './config.js';

export const collegesData = [
  {
    name: "Indian Institute of Technology, Bombay",
    location: "Powai, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    fees: 200000,
    rating: 4.8,
    type: "Public",
    established: 1958,
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&h=400&fit=crop",
    placementRate: 95,
    averagePackage: 2100000,
    highestPackage: 15000000,
    totalStudents: 10000,
    facultyCount: 650,
    campusSize: "550 acres",
    minRank: 1,
    maxRank: 500,
    description: "IIT Bombay is one of the premier engineering institutions in India, known for its excellence in technical education and research.",
    courses: ["B.Tech", "M.Tech", "PhD", "MBA"],
  },
  {
    name: "Indian Institute of Technology, Delhi",
    location: "Hauz Khas, New Delhi",
    city: "Delhi",
    state: "Delhi",
    fees: 210000,
    rating: 4.7,
    type: "Public",
    established: 1961,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    placementRate: 93,
    averagePackage: 2000000,
    highestPackage: 14500000,
    totalStudents: 9500,
    facultyCount: 600,
    campusSize: "320 acres",
    minRank: 1,
    maxRank: 600,
    description: "IIT Delhi is a leading technical university known for its academic excellence and innovation.",
    courses: ["B.Tech", "M.Tech", "PhD", "MBA", "MSc"],
  },
  {
    name: "National Institute of Technology, Trichy",
    location: "Tiruchirappalli",
    city: "Trichy",
    state: "Tamil Nadu",
    fees: 150000,
    rating: 4.5,
    type: "Public",
    established: 1964,
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&h=400&fit=crop",
    placementRate: 90,
    averagePackage: 1400000,
    highestPackage: 8500000,
    totalStudents: 8000,
    facultyCount: 450,
    campusSize: "800 acres",
    minRank: 500,
    maxRank: 3000,
    description: "NIT Trichy is one of the oldest and most prestigious NITs in India.",
    courses: ["B.Tech", "M.Tech", "MBA", "MCA"],
  },
  {
    name: "Birla Institute of Technology and Science, Pilani",
    location: "Pilani",
    city: "Pilani",
    state: "Rajasthan",
    fees: 450000,
    rating: 4.6,
    type: "Private",
    established: 1964,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    placementRate: 92,
    averagePackage: 1800000,
    highestPackage: 11000000,
    totalStudents: 18000,
    facultyCount: 800,
    campusSize: "328 acres",
    minRank: 1000,
    maxRank: 5000,
    description: "BITS Pilani is a premier private institute known for its academic rigor and industry connections.",
    courses: ["B.E", "M.Tech", "MBA", "PhD"],
  },
  {
    name: "Delhi University",
    location: "North Campus, Delhi",
    city: "Delhi",
    state: "Delhi",
    fees: 80000,
    rating: 4.3,
    type: "Public",
    established: 1922,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    placementRate: 75,
    averagePackage: 600000,
    highestPackage: 4000000,
    totalStudents: 25000,
    facultyCount: 1200,
    campusSize: "500 acres",
    minRank: 5000,
    maxRank: 15000,
    description: "Delhi University is one of India's oldest and most prestigious universities.",
    courses: ["BA", "BSc", "BCom", "MA", "MSc", "MCom"],
  },
  {
    name: "Vellore Institute of Technology",
    location: "Vellore",
    city: "Vellore",
    state: "Tamil Nadu",
    fees: 500000,
    rating: 4.4,
    type: "Private",
    established: 1984,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    placementRate: 88,
    averagePackage: 1200000,
    highestPackage: 8000000,
    totalStudents: 20000,
    facultyCount: 900,
    campusSize: "600 acres",
    minRank: 2000,
    maxRank: 8000,
    description: "VIT is a premier private engineering institution with excellent infrastructure and placements.",
    courses: ["B.Tech", "M.Tech", "MBA", "MCA"],
  },
  {
    name: "Manipal Institute of Technology",
    location: "Manipal",
    city: "Manipal",
    state: "Karnataka",
    fees: 480000,
    rating: 4.4,
    type: "Private",
    established: 1957,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    placementRate: 87,
    averagePackage: 1100000,
    highestPackage: 7500000,
    totalStudents: 15000,
    facultyCount: 700,
    campusSize: "550 acres",
    minRank: 2500,
    maxRank: 9000,
    description: "Manipal is a premier private engineering institute with global recognition.",
    courses: ["B.Tech", "M.Tech", "MBA", "MCA"],
  },
  {
    name: "BITS Hyderabad",
    location: "Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    fees: 430000,
    rating: 4.5,
    type: "Private",
    established: 2008,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    placementRate: 90,
    averagePackage: 1500000,
    highestPackage: 9500000,
    totalStudents: 5000,
    facultyCount: 300,
    campusSize: "250 acres",
    minRank: 1500,
    maxRank: 6000,
    description: "BITS Hyderabad offers quality education with strong industry connections.",
    courses: ["B.E", "M.Tech", "MBA"],
  },
  {
    name: "Anna University",
    location: "Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    fees: 120000,
    rating: 4.2,
    type: "Public",
    established: 1978,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    placementRate: 72,
    averagePackage: 500000,
    highestPackage: 3500000,
    totalStudents: 40000,
    facultyCount: 1500,
    campusSize: "700 acres",
    minRank: 8000,
    maxRank: 25000,
    description: "Anna University is a major engineering university in South India.",
    courses: ["B.E", "M.E", "MBA", "MCA"],
  },
  {
    name: "Mumbai University",
    location: "Fort, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    fees: 100000,
    rating: 4.1,
    type: "Public",
    established: 1857,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    placementRate: 70,
    averagePackage: 550000,
    highestPackage: 4200000,
    totalStudents: 30000,
    facultyCount: 1300,
    campusSize: "400 acres",
    minRank: 7000,
    maxRank: 20000,
    description: "Mumbai University is one of the oldest universities in India with diverse programs.",
    courses: ["BA", "BSc", "BCom", "BCS", "MA", "MSc"],
  },
];

export async function seedData() {
  await connectDatabase();
  const { colleges, counters } = getCollections();

  await resetCollections();

  const now = new Date().toISOString();
  const seededColleges = collegesData.map((college, index) => ({
    id: index + 1,
    name: college.name,
    location: college.location,
    city: college.city,
    state: college.state,
    fees: college.fees,
    rating: college.rating,
    type: college.type,
    established: college.established,
    image: college.image,
    placement_rate: college.placementRate,
    average_package: college.averagePackage,
    highest_package: college.highestPackage,
    total_students: college.totalStudents,
    faculty_count: college.facultyCount,
    campus_size: college.campusSize,
    min_rank: college.minRank,
    max_rank: college.maxRank,
    description: college.description,
    courses: college.courses,
    reviews: [
      {
        id: 1,
        author: 'Rahul Sharma',
        rating: 5,
        comment: 'Excellent infrastructure and world-class faculty. Best decision of my life!',
        course: 'B.Tech CSE',
        date: now,
      },
      {
        id: 2,
        author: 'Priya Patel',
        rating: 4,
        comment: 'Great placement opportunities. Campus life is amazing.',
        course: college.courses[0],
        date: now,
      },
    ],
    placements: [
      { id: 1, year: 2025, company: 'Google', package: 15000000, students_placed: 25 },
      { id: 2, year: 2025, company: 'Microsoft', package: 12000000, students_placed: 30 },
      { id: 3, year: 2024, company: 'Amazon', package: 11000000, students_placed: 28 },
    ],
    created_at: now,
    updated_at: now,
  }));

  await colleges.insertMany(seededColleges);

  await counters.insertMany([
    { _id: 'users', sequence_value: 0 },
    { _id: 'colleges', sequence_value: seededColleges.length },
    { _id: 'comparisons', sequence_value: 0 },
    { _id: 'questions', sequence_value: 0 },
    { _id: 'answers', sequence_value: 0 },
  ]);

  console.log('✅ MongoDB seeding completed successfully');
}

export async function seedDataIfEmpty() {
  await connectDatabase();
  const { colleges } = getCollections();

  const count = await colleges.countDocuments();

  if (count === 0) {
    await seedData();
  }
}

if (process.argv[1]?.includes('seed')) {
  seedData()
    .then(() => {
      console.log('Database seeding complete');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Failed to seed database:', error);
      process.exit(1);
    });
}
